all:
    # install pycocotools locally
	/kuacc/apps/anaconda/3.6/bin/python3 setup.py build_ext --inplace
	rm -rf build

install:
	# install pycocotools to the Python site-packages
	/kuacc/apps/anaconda/3.6/bin/python3 setup.py build_ext install
	rm -rf build
